export const getViteReactBaseFiles = () => {
  const files: Record<string, string> = {};

  files["index.html"] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Site</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  files["package.json"] = `{
  "name": "exhibit-export",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "deploy:netlify": "netlify deploy --prod --dir=dist",
    "deploy:vercel": "vercel --prod"
  },
  "dependencies": {
    "framer-motion": "^12.23.26",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.30.1"
  },
  "devDependencies": {
    "@types/react": "^18.3.23",
    "@types/react-dom": "^18.3.7",
    "@vitejs/plugin-react-swc": "^3.11.0",
    "autoprefixer": "^10.4.21",
    "postcss": "^8.5.6",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.8.3",
    "vite": "^7.2.7"
  }
}
`;

  files["tsconfig.json"] = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
`;

  files["vite.config.ts"] = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";

export default defineConfig({
  plugins: [react()],
});
`;

  files["tailwind.config.ts"] = `import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {}
  },
  plugins: []
} satisfies Config;
`;

  files["postcss.config.js"] = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
`;

  files["src/main.tsx"] = `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles/index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

  files["src/styles/index.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: light;
}

body {
  margin: 0;
  min-height: 100vh;
}
`;

  files["src/components/Section.tsx"] = `import { motion } from "framer-motion";
import type { ReactNode } from "react";
import { visualSystem, fontFamilies } from "../design/visualSystem";

type SectionProps = {
  children: ReactNode;
};

const getMotionProps = () => {
  if (visualSystem.motion.revealStyle === "none" || visualSystem.motion.durationScale === 0) {
    return null;
  }
  const distance = visualSystem.motion.revealStyle === "slide" ? 24 : 0;
  const opacity = visualSystem.motion.revealStyle === "fade" || visualSystem.motion.revealStyle === "slide";
  return {
    initial: { opacity: opacity ? 0 : 1, y: distance },
    whileInView: { opacity: 1, y: 0 },
    transition: { duration: 0.4 * visualSystem.motion.durationScale, ease: "easeOut" },
    viewport: { once: true, amount: 0.3 }
  };
};

export function Section({ children }: SectionProps) {
  const motionProps = getMotionProps();
  const content = (
    <div
      style={{
        maxWidth: visualSystem.spacing.contentMaxWidth,
        margin: "0 auto",
        padding: "0 24px",
        fontFamily: fontFamilies.body
      }}
    >
      {children}
    </div>
  );

  return (
    <section style={{ padding: \`\${visualSystem.spacing.sectionPadding}px 0\` }}>
      {motionProps ? <motion.div {...motionProps}>{content}</motion.div> : content}
    </section>
  );
}
`;

  files["README.md"] = `# Generated Site

This site was generated by Exhibit.

Some content may contain placeholders. Replace placeholders before final publication.

## Run locally
npm install
npm run dev

## Deploy
### Netlify
\`\`\`bash
npm install
npm run build
npx netlify deploy --prod --dir=dist
\`\`\`

### Vercel
\`\`\`bash
npm install
npm run build
npx vercel --prod
\`\`\`
`;

  return files;
};
